export const ENV_VAR_NAMES = {
  UPSTASH_REDIS_REST_URL: "UPSTASH_REDIS_REST_URL",
  UPSTASH_REDIS_REST_TOKEN: "UPSTASH_REDIS_REST_TOKEN",
  NEXT_PUBLIC_CONTACT_EMAIL: "NEXT_PUBLIC_CONTACT_EMAIL",
} as const;

export type EnvVarNames = typeof ENV_VAR_NAMES;
